# Generated by Django 5.1.7 on 2025-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(max_length=255, unique=True)),
                ('keyword', models.CharField(max_length=255)),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('full_response', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('result_count', models.IntegerField()),
                ('execution_time', models.FloatField()),
                ('cost', models.FloatField()),
            ],
            options={
                'ordering': ['-search_time'],
            },
        ),
    ]
